name: Update Account
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day

jobs:
  update-account:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Process Notion Changes
        run: python update_account.py
